#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "DeviceInformation" \
  --arg udid "$1" \
   --arg query_strings "$2" \
 '.udid = $udid 
  |.request_type = $request_type
  |.queries = ($query_strings | split(","))
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
