#!/bin/bash
source $MICROMDM_ENV_PATH
endpoint="v1/commands"
jq -n \
  --arg request_type "SetFirmwarePassword" \
  --arg udid "$1" \
  --arg currentpassword "$2" \
  --arg newpassword $3 \
  '.udid = $udid 
  |.currentpassword = $currentpassword 
  |.newpassword = $newpassword 
  |.request_type = $request_type
  '|\
  curl $CURL_OPTS -u "micromdm:$API_TOKEN" "$SERVER_URL/$endpoint" -d@-
